export const parrafo = [
  {
    id: 1,
    link: "https://dev.to/",
    imagen: "https://cdn-icons-png.flaticon.com/512/619/619032.png",
    alt: "Home",
    contenido: "Home",
  },
  {
    id: 2,
    link: "https://dev.to/readinglist",
    imagen: "https://cdn-icons-png.flaticon.com/512/262/262591.png",
    alt: "Reading List",
    contenido: "Reading List",
  },
  {
    id: 3,
    link: "https://dev.to/pod",
    imagen: "https://cdn-icons-png.flaticon.com/512/2204/2204947.png",

    alt: "Podcasts",
    contenido: "Podcasts",
  },
  {
    id: 4,
    link: "https://dev.to/videos",
    imagen: "https://cdn-icons-png.flaticon.com/512/8198/8198398.png",
    alt: "Videos",
    contenido: "Videos",
  },
  {
    id: 5,
    link: "https://dev.to/tags",
    imagen: "https://cdn-icons-png.flaticon.com/512/971/971115.png",
    alt: "Tags",
    contenido: "Tags",
  },
  {
    id: 6,
    link: "https://dev.to/help",
    imagen: "https://cdn-icons-png.flaticon.com/512/3336/3336017.png",
    alt: "Dev Help",
    contenido: "Dev Help",
  },
  {
    id: 7,
    link: "https://shop.forem.com/",
    imagen: "https://cdn-icons-png.flaticon.com/512/3081/3081559.png",
    alt: "Forem Shop",
    contenido: "Forem Shop",
  },
  {
    id: 8,
    link: "https://dev.to/advertise",
    imagen: "https://cdn-icons-png.flaticon.com/512/753/753252.png",
    alt: "Advertise on DEV",
    contenido: "Advertise on DEV",
  },
  {
    id: 9,
    link: "https://dev.to/showcase",
    imagen: "https://cdn-icons-png.flaticon.com/512/3266/3266390.png",
    alt: "DEV Showcase",
    contenido: "DEV Showcase",
  },
  {
    id: 10,
    link: "https://dev.to/about",
    imagen:
      "https://dev-to-uploads.s3.amazonaws.com/uploads/logos/resized_logo_UQww2soKuUsjaOGNB38o.png",
    alt: "About",
    contenido: "About",
  },
  {
    id: 11,
    link: "https://dev.to/contact",
    imagen: "https://cdn-icons-png.flaticon.com/512/1323/1323624.png",
    alt: "Contacts",
    contenido: "Contacts",
  },
  {
    id: 12,
    link: "https://dev.to/guides",
    imagen: "https://cdn-icons-png.flaticon.com/512/10433/10433045.png",
    alt: "Guides",
    contenido: "Guides",
  },
  {
    id: 13,
    link: "https://dev.to/software-comparisons",
    imagen: "https://cdn-icons-png.flaticon.com/512/983/983048.png",
    alt: "Software Comparisons",
    contenido: "Software Comparisons",
  },
];
